name: MLOPS CI Workflow 1

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: {}

jobs:
  e2e_mlops_workflow:
    runs-on: ubuntu-latest

    # services:
    #   fastapi:
    #     image: nitinnandeshwar/fastapi:dev
    #     ports:
    #       - 8000:8000

    #   streamlit:
    #     image: nitinnandeshwar/streamlit:dev
    #     ports:
    #       - 8501:8501
    #     env:
    #       API_URL: http://fastapi:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Preprocessing
        run: |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data.csv

      - name: Run Feature Engineering 
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl

      - name: setup mlflow Tracking Server 
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns


      - name: Run Model Training
        run: |
          python src/models/train_model.py \
            --config configs/model_config.yaml \
            --data data/processed/featured_house_data.csv \
            --models-dir models  \
            --mlflow-tracking-uri http://localhost:5555

      - name: Cleaning up mlflow server
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nitinnandeshwar/fastapi:${{ env.SHORT_SHA }}

      
      # - name: Build and Push 
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: nitinnandeshwar/fastapi:${{ substr(github.sha, 0, 7) }}
          # tags: nitinnandeshwar/fastapi:${{ github.sha::7 }}
      
